# Site settings
title: Git for Humanists
email: ssl2ab@virginia.edu
description: > # this means to ignore newlines until "baseurl:"
   Introduction to Git for Digital Humanists.
baseurl: "/git_slab" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shane_et_al
github_username:  ssl2ab

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
